### ISSUE TITLE
哪吒探针更新了，旧版不能用了

### ISSUE THREAD

**Issue by anglesccs** [frankiejun/serv00-play#15]
哪吒探针更新了，旧版不能用了

**Comment by frankiejun** [comment]
探针有一键更新的，更新后也不能用吗？

**Comment by anglesccs** [comment]
新版的配置文件改了，跟旧版的不一样了

**Comment by frankiejun** [comment]
我看了一下，哪吒面板升级到v1.0， 新版可能还不稳定，我目前使用的是 [哪吒监控](https://github.com/naiba/nezha) 0.20.12，很稳定。 没必要急着去追更，哪吒最大的功能就是监控服务器在线，以及一些性能指标，v0版已经够用。 建议你可以回退旧版使用。我这边暂不修改。
