### ISSUE TITLE
webssh启动失败

### ISSUE THREAD

**Issue by QINGHLS** [frankiejun/serv00-play#20]
webssh启动失败，查看日志后显示端口被占用，更换端口无果，若把改为给sanpanel，sanpanel可以正常使用该端口，可以排除端口的问题

**Comment by QINGHLS** [comment]
使用的是s15的机器

**Comment by frankiejun** [comment]
先初始化机器，当新机器重新操作一次，由脚本自己分配端口，你别掺和。

**Comment by QINGHLS** [comment]
一样的结果
![image](https://github.com/user-attachments/assets/8ce03233-c564-4c93-946a-87ab3fcbe5fc)
![image](https://github.com/user-attachments/assets/d39905b8-61aa-49cd-986d-8ce8a94914b7)

**Comment by QINGHLS** [comment]
我发现了webssh在正常运行，但只是脚本显示失败，谢谢你，这或许只是一个显示错误？
