### ISSUE TITLE
批量保活执行失败，

### ISSUE THREAD

**Issue by LYXCQX** [frankiejun/serv00-play#21]
2s
##[group***Run chmod +x ./revive.sh
chmod +x ./revive.sh
./revive.sh
shell: /usr/bin/bash -e ***0***
env:
  HOSTS_JSON:  ***
  TELEGRAM_TOKEN: 
  TELEGRAM_USERID: 
  WXSENDKEY: 
  SENDTYPE: 
##[endgroup***
Warning: Permanently added 's[1](https://github.com/LYXCQX/serv00-play/actions/runs/12380550250/job/34557185061#step:4:1)4.serv00.com' (ED25519) to the list of known hosts.
bash: line 1: /home/leyuanlove/serv00-play/keepalive.sh: Permission denied
output:
登录失败
未配置TG推送

s请问这是什么情况，我应该怎么做

**Comment by frankiejun** [comment]
/home/leyuanlove/serv00-play/keepalive.sh 没赋权。
上去选1更新一下就行
