### ISSUE TITLE
同步代码失败

### ISSUE THREAD

**Issue by oahxu** [frankiejun/serv00-play#23]
同步您最新代码时，workflows报错，看这个项目没有使用token啊 
! [remote rejected] main -> main (refusing to allow a GitHub App to create or update workflow `.github/workflows/deploy.yml` without `workflows` permission)

**Comment by frankiejun** [comment]
那个disable掉就可以了。  当时是方便同步deploy.yml那个workflow搞的，但现在稳定基本不会再改，可以不要了
https://t.me/fanyou_channel/53
