### ISSUE TITLE
Vmess+Websocket  

### ISSUE THREAD

**Issue by Ahmad-2213** [frankiejun/serv00-play#6]
Hello there , I encounter this error on V2ray.
also , I've noticed that mux won't work propely and failes.

failed to process outbound traffic > proxy/vmess/outbound: connection ends > websocket: close 1006 (abnormal closure): unexpected EOF

**Comment by frankiejun** [comment]
For more information about the usage of Vmess+ws, you can refer to my youtube video (it's in the readme). The first time the script outputs a link it doesn't work right away, you need to go to cloudflare to do the proxy and the origin rule setting.

**Comment by Ahmad-2213** [comment]
I can connect to the link, I just happen to inform that there is mux issue and some minor errors...
btw , is there any ways to sign up for ct8.pl? it says that has sent a message to email , but nothing is sent actually.
