### ISSUE TITLE
Ram exceed

### ISSUE THREAD

**Issue by Ahmad-2213** [frankiejun/serv00-play#7]
please add Ram limitations in keepalive for if the singbox gone over 512 MB usage , then restart it.
my link went EOF and i saw that it's using 1400 MB ram whereas the limitation defined for it is 512 !
I restart it and the issue gone. but for automate this process it's fully demanding adding a parameter to  restart the singbox if it exceeded the limitations.

**Comment by frankiejun** [comment]
I'm guessing you must have opened Vless. Please don't use Vless, as it has high memory usage. The Sing-box program shouldn't take up that much memory, and if you are experiencing this, please take a screenshot.

**Comment by Ahmad-2213** [comment]
No I'm currently using vmess only.

**Comment by Ahmad-2213** [comment]
it's like an app crash or something that uses high values of memory.
I had to restart the singbox to fix this issue.
if it happened again , I'll take a screenshot of that page to give the idea that there is similar issue happening,  however, to prevent this type of issue for any reason , it's necessary to define a parameter in keepalive to check the status of resources and see if the usage exceeds the limitaions so that you can restart the singbox core to fix the issue.
optionally , you can define some parameters to see if the exceeded time is under 10 seconds , cause maybe sometimes you don't need to restart singbox because it has exceeded the limitations for 1-2 seconds .

**Comment by Ahmad-2213** [comment]
![image](https://github.com/user-attachments/assets/c64bbacd-c0dc-48e2-9cb1-8896ba91e12b)
![image](https://github.com/user-attachments/assets/4dd25641-af70-4eaa-a04b-24652fc0ae83)

as you can see , it uses over the limitations and returns EOF in v2ray clients.
maybe we need figure this out...

**Comment by frankiejun** [comment]
How did you manage to make it consume so much memory? What did you do, and how can I reproduce the problem?

**Comment by Ahmad-2213** [comment]
> How did you manage to make it consume so much memory? What did you do, and how can I reproduce the problem?

well, I have no Idea , maybe because 2 or 3 of my friends using this link, it happens 1 or 2 days after starting singbox.
is there anything related to domain settings in cloudflare?

**Comment by Ahmad-2213** [comment]
> > How did you manage to make it consume so much memory? What did you do, and how can I reproduce the problem?
> 
> well, I have no Idea , maybe because 2 or 3 of my friends using this link, it happens 1 or 2 days after starting singbox. is there anything related to domain settings in cloudflare?

is that a big matter to add a parameter that restarts the singbox after exceeding the limitations?
cause if even a lot of people were connected to the link and then disconnect , it must come under limitations after they are disconnected from it.
but it seems to be a bug or something rather than a problem, meaning that if it exceeded the limitations , it would caught right there or maybe after a specific time , it goes higher than the limitations.
the inevitable matter is to set a parameter which restarts the singbox after it exceeded the limitations.
